// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/subscribe/clash': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subscribe/clash').default>>>>
    }
    '/api/subscribe/mihomo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subscribe/mihomo').default>>>>
    }
    '/api/subscribe/v2ray': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subscribe/v2ray').default>>>>
    }
  }
}
export {}